name: Code Format

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  carog-format:
    strategy:
      matrix:
        # Supported GitHub-hosted runners and hardware resources
        # see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        os: [ubuntu-22.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Cache of Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ matrix.os }}-${{ runner.os }}-${{ runner.arch }}-cargo-clippy

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: rustfmt
        toolchain: nightly

    - name: Cargo +nightly fmt --all -- --check
      run: make check-fmt

    - name: Install cargo-sort
      run: |
        which cargo-sort >/dev/null && echo "cargo-sort is installed" \
        || (echo "cargo-sort is not installed" && cargo install cargo-sort)

    - name: check-sort
      run: make check-sort
